# Generated by Django 3.0.6 on 2020-07-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='ans',
            field=models.TextField(null=True),
        ),
    ]
