# Generated by Django 3.0.6 on 2020-07-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_story', '0002_flag_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='checkpoint',
            field=models.TextField(null=True),
        ),
    ]
