# Generated by Django 3.0.6 on 2020-07-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_story', '0003_flag_checkpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
