# Generated by Django 3.0.6 on 2020-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_story', '0004_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_table',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
